# Generated by Django 5.2.17 on 2026-09-28 11:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0003_remove_telegramdelivery_unique_session_account_category_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable ID; never collect passwords or payment card details.', unique=True)),
                ('label', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('text', 'Short text'), ('email', 'Email'), ('textarea', 'Long text'), ('select', 'Dropdown'), ('date', 'Preferred date'), ('checkbox', 'Checkbox')], default='text', max_length=12)),
                ('choices', models.TextField(blank=True, help_text='One dropdown choice per line.')),
                ('required', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('event_name', models.CharField(default='conversion', help_text='Must exist in analytics/services.py ALLOWED_EVENTS, or be a server-side event.', max_length=80)),
                ('target', models.CharField(blank=True, help_text='Optional goal_key, target or CTA ID to match.', max_length=100)),
                ('primary', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('benefit', 'Benefit'), ('step', 'How it works'), ('faq', 'FAQ'), ('testimonial', 'Testimonial')], default='benefit', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('attribution', models.CharField(blank=True, help_text='For genuine, approved customer quotes only.', max_length=150)),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your business', max_length=120)),
                ('tagline', models.CharField(default='A thoughtful approach. A better outcome.', max_length=160)),
                ('headline', models.CharField(default='Your next chapter starts with a conversation.', max_length=200)),
                ('description', models.TextField(default='Tell us what you have in mind. We’ll help you find a clear, practical path forward, with personal attention at every step.')),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('hero_image', models.ImageField(blank=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#31594f', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')])),
                ('cta_label', models.CharField(default='Let’s talk', max_length=70)),
                ('conversion_mode', models.CharField(choices=[('form', 'Contact / quote form'), ('booking', 'Booking request'), ('external', 'External scheduling link')], default='form', max_length=20)),
                ('booking_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('thank_you', models.CharField(default='Thank you. Your request is safely with us, and we’ll be in touch soon.', max_length=300)),
                ('privacy_notice', models.TextField(default='We use your submitted details to respond to your request. With your permission, first-party analytics records visits, interactions, campaign attribution, device information and IP-based approximate location. Authorized team members may receive journey summaries through Telegram. Analytics is retained for 180 days. Contact us to request access or deletion.')),
                ('analytics_mode', models.CharField(choices=[('consent', 'Ask permission'), ('off', 'Disabled'), ('essential', 'Always on (check your legal basis)')], default='consent', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='form', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('won', 'Won'), ('lost', 'Lost'), ('spam', 'Spam')], default='new', max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('consent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='analytics.visitorsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
