# Generated by Django 5.2.17 on 2026-09-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Site settings'},
        ),
    ]
