# Generated by Django 5.2.5 on 2026-08-05 12:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(db_index=True)),
                ('session_id', models.UUIDField(unique=True)),
                ('landing_path', models.CharField(default='/', max_length=500)),
                ('initial_referrer', models.URLField(blank=True, max_length=2000)),
                ('source', models.CharField(db_index=True, default='direct', max_length=150)),
                ('medium', models.CharField(blank=True, max_length=120)),
                ('campaign', models.CharField(blank=True, max_length=200)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_class', models.CharField(blank=True, max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('os_name', models.CharField(blank=True, max_length=100)),
                ('browser_name', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('timezone_name', models.CharField(blank=True, max_length=100)),
                ('human_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('funnel_stage', models.CharField(db_index=True, default='landed', max_length=80)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('digest_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('telegram_message_id', models.CharField(blank=True, max_length=100)),
                ('geo_enriched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['-first_seen_at', 'source'], name='analytics_v_first_s_8ba2ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('contacted', 'Contacted'), ('meeting', 'Meeting booked'), ('won', 'Won'), ('lost', 'Lost'), ('spam', 'Spam')], db_index=True, default='new', max_length=20)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('calendly_opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='analytics.visitorsession')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('path', models.CharField(default='/', max_length=500)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.visitorsession')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['session', 'occurred_at'], name='analytics_e_session_25948a_idx'), models.Index(fields=['name', '-occurred_at'], name='analytics_e_name_eeec35_idx')],
            },
        ),
    ]
