# Generated by Django 5.2.5 on 2026-08-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_iprecord_telegrambotstate_visitorsession_ip_record_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='telegramdelivery',
            name='unique_session_account_category_delivery',
        ),
    ]
