# Generated by Django 5.2.17 on 2026-09-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_telegramdelivery_unique_session_account_category_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='calendly_opened_at',
        ),
        migrations.AddField(
            model_name='lead',
            name='booking_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
